module.exports={

    'Number':{'id':'class', 'type':'Number'},
    'String':{'id':'class', 'type':'String'},
    'Object':{'id':'class', 'type':'Object'},
    'RegExp':{'id':'class', 'type':'RegExp'},
    'Error':{'id':'class', 'type':'Error'},
    'EvalError':{'id':'class', 'type':'EvalError'},
    'RangeError':{'id':'class', 'type':'RangeError'},
    'ReferenceError':{'id':'class', 'type':'ReferenceError'},
    'SyntaxError':{'id':'class', 'type':'SyntaxError'},
    'TypeError':{'id':'class', 'type':'TypeError'},
    'URIError':{'id':'class', 'type':'URIError'},
    'Function':{'id':'class', 'type':'Function'},
    'Date':{'id':'class', 'type':'Date'},
    'Boolean':{
        'id':'class',
        'type':'Boolean',
        'proto':{
            'valueOf':{'type':'Boolean','id':'function','param':[]}
        }

    },
    'Symbol':{'id':'class', 'type':'Symbol'},
    'Atomics':{'id':'class', 'type':'Atomics'},
    'DataView':{
        'id':'class',
        'type':'DataView',
        'static':{},
        'properties':{
            'buffer':'ArrayBuffer',
            'byteLength':'Number',
            'byteOffset':'*',
        },
        'methods':{
            'getInt8':'*',
            'getUint8':'*',
            'getInt16':'*',
            'getUint16':'*',
            'getInt32':'*',
            'getUint32':'*',
            'getFloat32':'*',
            'getFloat64':'*',
            'setInt8':'*',
            'setUint8':'*',
            'setInt16':'*',
            'setUint16':'*',
            'setInt32':'*',
            'setUint32':'*',
            'setFloat32':'*',
            'setFloat64':'*',
        },
    },
    'Array':{
        'id':'class',
        'type':'Array',
        'static':{
            'from':'Array',
            'isArray':'Boolean',
            'of':'Array',
        },
        'proto':{
            'length':{'type':'Number','id':'const'},
            'concat':'Array',
            'copyWithin':'Array',
            'entries':'Iterator',
            'every':'Boolean',
            'fill':'Array',
            'filter':'Array',
            'find':'*',
            'findIndex':'Number',
            'forEach':'undefined',
            'includes':'Boolean',
            'indexOf':'Number',
            'join':'String',
            'keys':'Iterator',
            'lastIndexOf':'Number',
            'map':'Array',
            'pop':'*',
            'push':{'type':'Number','id':'function','param':['*']},
            'reduce':'*',
            'reduceRight':'*',
            'reverse':'Array',
            'shift':'*',
            'slice':'Array',
            'some':'Boolean',
            'sort':'Array',
            'splice':{'type':'Array','id':'function','param':['*']},
            'toLocaleString':'String',
            'toSource':'String',
            'toString':'String',
            'unshift':'Number',
            'values':'Iterator',
        },
    },
    'ArrayBuffer':{},
    'Float32Array':{},
    'Float64Array':{},
    'Int16Array':{},
    'Int32Array':{},
    'Int8Array':{},
    'Intl':{
        'static':{
            'DateTimeFormat':'*',
            'NumberFormat':'*',
            'Collator':'*',
        },
        'properties':{},
        'methods':{},
    },
    'Iterator':{},
    'JSON':{},
    'ParallelArray':{},
    'Promise':{},
    'Proxy':{},
    'Reflect':{},
    'SIMD':{
        'static':{
            'Bool16x8':'*',
            'Bool32x4':'*',
            'Bool64x2':'*',
            'Bool8x16':'*',
            'Float32x4':'*',
            'Float64x2':'*',
            'Int16x8':'*',
            'Int32x4':'*',
            'Int8x16':'*',
            'Uint16x8':'*',
            'Uint32x4':'*',
            'Uint8x16':'*',
        },
        'properties':{},
        'methods':{},
    },
    'Set':{},
    'SharedArrayBuffer':{},
    'StopIteration':{},
    'TypedArray':{},
    'URIError':{},
    'Uint16Array':{},
    'Uint32Array':{},
    'Uint8Array':{},
    'Uint8ClampedArray':{},
    'WeakMap':{},
    'WeakSet':{},
}